# Site settings
title: BradyLiles.github.io
email: bradyliles@outlook.com
description: "Brady Liles GitHub Repository and Blog"
logo_location: "https://avatars2.githubusercontent.com/u/3682933?v=3&s=460"

#baseurl:
url: http://www.bradyliles.github.io

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments

#Other Global Configuration
exclude: ['README.md']
